ImplementCors_Demo/Models/ErrorViewModel.cs
namespace ImplementCors_Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImplementCors_Demo/Models/StudentsViewModel.cs
namespace ImplementCors_Demo.Models
{
    public class StudentsViewModel
    {
        public int Id { get; set; } 
        public string? Name { get; set; }
        public int Age { get; set; }    
        public string? Address { get; set; } 
    }
}

ImplementCors_Demo/Controllers/HomeController.cs
using ImplementCors_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ImplementCors_Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImplementCors_Demo/Controllers/StudentController.cs
using ImplementCors_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;

namespace ImplementCors_Demo.Controllers
{
    public class StudentController : Controller
    {
        private readonly string BASE_URL = "https://localhost:7059/Student/";
        HttpClient client = new HttpClient();
        public IActionResult Index()
        {
            HttpResponseMessage response = client.GetAsync(BASE_URL+ "GetAllStudents").Result;
            var stringData= response.Content.ReadAsStringAsync().Result;
            var data = JsonConvert.DeserializeObject<List<StudentsViewModel>>(stringData);

            return View(data);
        }
        public IActionResult CORS()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Post()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Post(StudentsViewModel students)
        {
            try
            {
                HttpRequestMessage request = new HttpRequestMessage();
                var data = JsonConvert.SerializeObject(students);
                var contentData = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
                HttpResponseMessage response = client.PostAsync(BASE_URL + "PostStudents", contentData).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(CORS));
                }
                else
                {
                    return BadRequest();
                }
            }
            catch
            {
                return BadRequest();    
            }

        }
    }
}

ImplementCors_Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ImplementCors_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImplementCors_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  

    <link rel="stylesheet" href="~/ImplementCors_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImplementCors_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="CORS">Cors Example</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Post">Post Example</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ImplementCors_Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ImplementCors_Demo/Views/Student/CORS.cshtml
<div>
    <center><h1>Cors Example</h1></center>
    <table class="table table-strip">
        <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Age</th>
                <th>Address</th>
            </tr>
        <tbody id="MyData">
            

        </tbody>
    </table>
</div>
<script>
    $(document).ready(function(){
        $.ajax({
            type:"GET",
            url:"https://localhost:7059/Student/GetAllStudents",
            dataType: 'json',
            success:function(response){
                $("#MyData").empty();
                $.each(response ,function(name,value){
                    $("#MyData").append('<tr><td>'+value.Id+'</td><td>'+value.Name+'</td><td>'+value.Age+'</td><td>'+value.Address+'</td></tr>');
                });
                
            }
            

        });
 });
</script>

ImplementCors_Demo/Views/Student/Index.cshtml
@model IEnumerable<ImplementCors_Demo.Models.StudentsViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            
        </tr>
}
    </tbody>
</table>

ImplementCors_Demo/Views/Student/Post.cshtml
<div class="container">
    <div>
        <form method="post">
            <div class"form-group">
                <label for="id" >Id:</label>
            <input class="form-control" type="number" id="id" name="id" /><br />

            </div>

            <div class="form-group">
                <label for="Name" >Name:</label>
            <input class="form-control" type="text" id="name" name="name" /><br />
            </div>

           <div class="form-group">
                <label for="Age" >Age:</label>
            <input class="form-control" type="number" id="age" name="Age" /><br />
           </div>

            <div class="form-group">
                <label for="address" >Address:</label>
            <input class="form-control" type="text" id="address" name="Address" /><br />
            </div>
            <br />
            <input type="submit" name="submit" value="submit" id="submit" />


        </form>
    </div>

</div>
<script>
    $(document).ready(function(){
        
        $("#submit").click(function(){
            var id=$("#id").val();
            var name=$("#name").val();
            var age=$("#age").val();
            var address=$("#address").val();
            mydata={"Id":id,"Name":name,"Age":age,"Address":address};
            
             $.ajax({
            type:"POST",
            url:"Student/Post",
            data:mydata,
            success:function(res){
                window.alert("Done...")

            }
        })

        });

    });
</script>